Models/ApplicationDBCOntext.cs
using Microsoft.EntityFrameworkCore;

namespace MyWorkDetailsProject.Models
{
    public class ApplicationDBCOntext:DbContext
    {
        public ApplicationDBCOntext(DbContextOptions<ApplicationDBCOntext> options ) :base(options)
        { 
        }
        public DbSet<Login> logins { get; set; }
        public DbSet<Register> registers { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Login>().ToTable("Login").HasKey(lg => new
            {
                lg.UserID
            }); 
            modelBuilder.Entity<Register>().ToTable("Register").HasKey(rg => new
            {
                rg.UserID
            });
            base.OnModelCreating(modelBuilder);
        }
    }
}

Models/ErrorViewModel.cs
namespace MyWorkDetailsProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Login.cs
namespace MyWorkDetailsProject.Models
{
    public class Login
    {
        public string? UserID { get; set; }
        public string? Password { get; set; }
    }
}

Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MyWorkDetailsProject.Models
{
    public class LoginViewModel
    {
        [Required]
        public string UserID { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

Models/Register.cs
namespace MyWorkDetailsProject.Models
{
    public class Register
    {
        public string? UserID { get; set; }
        public string? FName { get; set; }
        public string? LName { get; set; }
        public string? Gender { get;set; }
        public string? Email { get; set; }
        public string? Phone { get; set; }
        public string? City { get; set; }
        public string? Country { get; set; }
        public string? Password { get; set; }
        public string? ConfirmPassword { get; set; }
    }
}

Models/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MyWorkDetailsProject.Models
{
    public class RegisterViewModel
    {
        [Key]
        [Required]
        [Display(Name = "User Name")]
        public string? UserID { get; set; }
        [Required(ErrorMessage = "Please Enter First Name..")]
        [Display(Name = "First Name")]
        public string? FName { get; set; }
        [Required(ErrorMessage = "Please Enter Last Name..")]
        [Display(Name = "Last Name")]
        public string? LName { get; set; }
        [Required(ErrorMessage = "Please Enter Gender..")]
        public string? Gender { get; set; }
        [Required(ErrorMessage = "Please Enter Email Id..")]
        public string? Email { get; set; }
        [Required(ErrorMessage = "Please Enter Mobile Number..")]
        public string? Phone { get; set; }
        [Required(ErrorMessage = "Please Enter City..")]
        public string? City { get; set; }
        [Required(ErrorMessage = "Please Enter Country..")]
        public string? Country { get; set; }
        [Required(ErrorMessage = "Please Enter Password...")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string? Password { get; set; }
        [Required(ErrorMessage = "Please Enter the Confirm Password...")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare("Password")]
        public string? ConfirmPassword { get; set; }
    }
}

Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyWorkDetailsProject.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyWorkDetailsProject.Models;
using System.Diagnostics;
using NLog;

namespace MyWorkDetailsProject.Controllers
{
    public class HomeController : Controller
    {
        private static readonly Logger _logger = LogManager.GetCurrentClassLogger();

        //public HomeController(ILogger<HomeController> logger)
        //{
        //    _logger = logger;
        //}

        public IActionResult Index()
        {
            TempData["UserID"] = "Durga Prasad";
            _logger.Info("Calling Index Method");
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginRegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using MyWorkDetailsProject.Models;

namespace MyWorkDetailsProject.Controllers
{
    
    public class LoginRegistrationController : Controller
    {
        private readonly ApplicationDBCOntext _applicationDBCOntext;
        public LoginRegistrationController(ApplicationDBCOntext applicationDBCOntext) 
        {
            _applicationDBCOntext = applicationDBCOntext;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Login()
        {
            HttpContext.Session.SetString("Name", "Durga Prasad");
            ViewBag.title = "Login";
            return View();
        }
        [HttpPost]
        public IActionResult Login(Login login)
        {
            
            if(ModelState.IsValid)
            {
                var userid=login.UserID;
                var password=login.Password;
                var result= _applicationDBCOntext.logins.SingleOrDefault(ml=>ml.UserID== userid && ml.Password == password);
                if(result==null)
                {
                    return Content($"{userid} is not found in DB");
                }
                else
                {
                    
                    TempData["UserID"] = userid;
                    HttpContext.Session.SetString("UserID", userid);
                    Response.Cookies.Append("UserName", userid);
                    
                    //ViewBag.UserID = userid;
                    //ViewData["UserID"] = userid;
                    return RedirectToAction(nameof(HomeController.Index), "Home");
                    //return Content($"{userid} Successfully Logged In");
                }
                
            }
            else
            {
                return Content("Error");
            }

           
        }
        [HttpGet]
        public IActionResult Register()
        {
            ViewData["Title"] = "Register";
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(Register register)
        {
            if(ModelState.IsValid)
            {
                var userid=register.UserID;
                var fname = register.FName;
                var lname=register.LName;
                var gender=register.Gender;
                var email=register.Email;
                var phone=register.Phone;
                var city=register.City;
                var country=register.Country;
                var password=register.Password;
                var confirmpassword = register.ConfirmPassword;

               await  _applicationDBCOntext.registers.AddAsync(register);
                await _applicationDBCOntext.SaveChangesAsync();
               await _applicationDBCOntext.logins.AddAsync(new Models.Login
                {
                    UserID= userid,
                    Password= password
                });
               await  _applicationDBCOntext.SaveChangesAsync();
               // ViewBag.UserID = userid;
                return RedirectToAction("Login");
                
            }
            else
            {
                return View();
            }
          
        }
    }
}

Views/Admin/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Admin/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor;

@{
    ViewData["Title"] = "Home Page";
    var message = TempData["UserID"] as string;
    var userid = HttpContextAccessor?.HttpContext?.Session.GetString("UserID");
    var cookieuserid = HttpContextAccessor?.HttpContext?.Request.Cookies["UserName"];
}
<div class="text-center">
    
    <h1 class="display-4">Welcome to TempData @message and Session @userid and Cookies @cookieuserid</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/LoginRegistration/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/LoginRegistration/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <title>@ViewBag.title</title>
}
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor;
@model MyWorkDetailsProject.Models.LoginViewModel;
<html>
    <head>
    <h1>Login Form</h1>
    <h2>@HttpContextAccessor?.HttpContext?.Session.GetString("Name")</h2>
    </head>
    <body>
      <form role="form" asp-action="Login" asp-controller="LoginRegistration" method="post">
          <table>
            <tr>
                <td>
                    <label for="UserID">User ID</label>
                </td>
                <td>
                    <input type="text" name="UserID" asp-for="UserID" autocomplete="off" placeholder="UserID">
                    <span asp-validation-for="UserID" class="text-danger"></span>
                </td>
            </tr>
                <tr>
                    <td>
                    <label for="Password">Password</label><br />
                    </td>
                    <td>
                    <input type="password" name="Password" asp-for="Password" autocomplete="off" placeholder="Password" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                    </td>
                </tr>
          </table>
        <input type="submit" value="Login" class="btn btn-info btn-block" />
      </form>
    </body>
</html>

Views/LoginRegistration/Register.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
<title>@ViewData["Title"]</title>
}
@model MyWorkDetailsProject.Models.RegisterViewModel;
<html>
    <head>
        <h1>Register Form</h1>
    </head>
    <body>
        <form role="form" asp-action="Register" asp-controller="LoginRegistration" method="post">
            <table>
                <tr>
                    <td><label for="UserID">UserID</label> </td>
                    <td><input type="text" name="UserID" asp-for="UserID" placeholder="UserID" autocomplete="off" />
                    <span asp-validation-for="UserID" class="text-danger"></span>
                </td>
                </tr>
                <tr>
                    <td><label for="FName">First Name</label> </td>
                    <td><input type="text" name="FName" asp-for="FName" autocomplete="off" placeholder="FName" />
                        <span asp-validation-for="FName" class="text-danger"></span></td>
                </tr>
            <tr>
                <td><label for="LName">Last Name</label> </td>
                <td>
                    <input type="text" name="LName" asp-for="LName" autocomplete="off" placeholder="LName" />
                    <span asp-validation-for="LName" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <td><label for="Gender">Gender</label> </td>
                <td>
                    <input type="text" name="Gender" asp-for="Gender" autocomplete="off" placeholder="Gender" />
                    <span asp-validation-for="Gender" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <td><label for="Email">Email ID</label> </td>
                <td>
                    <input type="text" name="Email" asp-for="Email" autocomplete="off" placeholder="Email" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <td><label for="Phone">Mobile Number</label> </td>
                <td>
                    <input type="text" name="Phone" asp-for="Phone" autocomplete="off" placeholder="Phone" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <td><label for="City">City</label> </td>
                <td>
                    <input type="text" name="City" asp-for="City" autocomplete="off" placeholder="City" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <td><label for="Country">Country</label> </td>
                <td>
                    <input type="text" name="Country" asp-for="Country" autocomplete="off" placeholder="Country" />
                    <span asp-validation-for="Country" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <td><label for="Password">Password</label> </td>
                <td>
                    <input type="password" name="Password" asp-for="Password" autocomplete="off" placeholder="Password" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <td><label for="ConfirmPassword">Confirm Password</label> </td>
                <td>
                    <input type="password" name="ConfirmPassword" asp-for="ConfirmPassword" autocomplete="off" placeholder="ConfirmPassword" />
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </td>
            </tr>
            </table>
            <br />
            <br />
        <input type="submit" value="Register" class="btn btn-info btn-block" />
        </form>
    </body>
</html>

Views/Shared/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyWorkDetailsProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">MyWorkDetailsProject-Admin</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoginRegistration" asp-action="Index">Login Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoginRegistration" asp-action="Login">Login Form</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoginRegistration" asp-action="Register">Register Form</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="About">Admin About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Privacy">Admin Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MyWorkDetailsProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyWorkDetailsProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyWorkDetailsProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyWorkDetailsProject-Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoginRegistration" asp-action="Index">Login Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoginRegistration" asp-action="Login">Login Form</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoginRegistration" asp-action="Register">Register Form</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="About">Admin About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Privacy">Admin Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MyWorkDetailsProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LoginRegLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyWorkDetailsProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="LoginRegistration" asp-action="Index">MyWorkDetailsProject-Log Registration</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoginRegistration" asp-action="Index">Login Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoginRegistration" asp-action="Login">Login Form</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoginRegistration" asp-action="Register">Register Form</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="About">Admin About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Privacy">Admin Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MyWorkDetailsProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>